### ISSUE TITLE
请问agent问答（使用工具）和RAG问答是如何做路由的？

### ISSUE THREAD

**Issue by dongteng** [shibing624/ChatPilot#10]
### Describe the Question
Please provide a clear and concise description of what the question is.

如题，我阅读了您的代码，是不是没做这个路由呢？agent问答是单独的，RAG问答也是单独的

**Comment by shibing624** [comment]
rag把文档内容加入prompt中，路由到正常的llm中，兼容实现。

**Comment by dongteng** [comment]
> rag把文档内容加入prompt中，路由到正常的llm中，兼容实现。

可能是我没表述清楚。我知道RAG的流程，是将检索到的内容放到prompt中。
我的意思是您的RAGFusion这个类与ChatAgent这个类如何集成的呢？
就是在对话过程中，既可以RAG又可以url解析、python解释器等。 这块的代码我没太看懂在哪里。

不过您的这个agent调用工具的效果很好，我用vllm部署了qwen,使用ChatAgent效果不错。

我的理解可不可以把RAG也包装一下，成为一个跟url解析一样的工具呢？

**Comment by shibing624** [comment]
加断点，调试看下代码。
