### ISSUE TITLE
error usage of type hint

### ISSUE THREAD

**Issue by GodsDusk** [shibing624/ChatPilot#6]
### Describe the bug
![image](https://github.com/shibing624/ChatPilot/assets/13726533/f7a6c628-ce2b-4fa4-9ead-58acf2f89c22)

it will cause TypeError: 'type' object is not subscriptable

same error in litellm==1.30.7

<img width="775" alt="image" src="https://github.com/shibing624/ChatPilot/assets/13726533/dcf113ab-f7c0-40d3-b48a-17fb1feb4fbf">

**Comment by shibing624** [comment]
litellm==1.26.8
