### ISSUE TITLE
打开页面为空

### ISSUE THREAD

**Issue by lonngxiang** [shibing624/ChatPilot#8]
我是直接前端解压buid.zip，后端直接启动start.sh，还需要设置什么吗，不如.env，怎么填入自定义大模型地址

前端页面打开为空
![image](https://github.com/shibing624/ChatPilot/assets/40717349/7a255aec-4f34-4293-864c-9a5030009c1d)

命令行输出
![image](https://github.com/shibing624/ChatPilot/assets/40717349/64962f0d-3f16-4f13-8f62-5991a7679c28)

**Comment by shibing624** [comment]
参考.env.example设置.env, 打开0.0.0.0:9090

**Comment by lonngxiang** [comment]
> 参考.env.example设置.env, 打开0.0.0.0:9090

如果是ollama、vllm的openai 接口要怎么设置呢
